<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Jayarees-MacBook-Pro.local" name="Stepdef.Cornwall_Register" tests="6" failures="1" timestamp="11 Sep 2019 09:35:07 GMT" time="261.234" errors="0">
  <testcase name="i_am_not_a_user_of_agate_on_cornwall_and_I_open_a_browser" time="1.780" classname="Stepdef.Cornwall_Register"/>
  <testcase name="i_navigate_to_a_premium_article_on_cornwall" time="12.648" classname="Stepdef.Cornwall_Register"/>
  <testcase name="i_click_on_the_create_wallet_button_of_reaction_first_use_notice_cornwall" time="78.672" classname="Stepdef.Cornwall_Register"/>
  <testcase name="i_verify_that_the_create_wallet_button_on_reaction_first_use_notice_takes_me_to_the_reg_page_on_cornwall" time="22.035" classname="Stepdef.Cornwall_Register"/>
  <testcase name="i_enter_all_the_details_successfully_on_the_reg_page_on_cornwall" time="61.159" classname="Stepdef.Cornwall_Register"/>
  <testcase name="i_am_registered_as_an_agate_user_on_cornwall_successfully_and_I_am_shown_a_first_use_notice" time="84.940" classname="Stepdef.Cornwall_Register">
    <failure type="java.lang.AssertionError" message="expected:&lt;0.2&gt; but was:&lt;-7.8&gt;">
      <![CDATA[java.lang.AssertionError: expected:<0.2> but was:<-7.8>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Cornwall_Register.i_am_registered_as_an_agate_user_on_cornwall_successfully_and_I_am_shown_a_first_use_notice(Cornwall_Register.java:256)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- i_am_registered_as_an_agate_user_on_cornwall_successfully_and_I_am_shown_a_first_use_notice -->
</testsuite> <!-- Stepdef.Cornwall_Register -->
