<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Jayarees-MacBook-Pro.local" name="Stepdef.Cornwall_Login_from_FUN" tests="6" failures="1" timestamp="11 Sep 2019 09:35:07 GMT" time="111.041" errors="0">
  <testcase name="i_am_a_registered_user_of_Cornwall_and_I_open_a_browser" time="0.856" classname="Stepdef.Cornwall_Login_from_FUN"/>
  <testcase name="i_navigate_to_a_premium_article_on_Cornwall" time="14.074" classname="Stepdef.Cornwall_Login_from_FUN"/>
  <testcase name="i_click_on_Login_from_Cornwall_First_use_notice" time="31.128" classname="Stepdef.Cornwall_Login_from_FUN"/>
  <testcase name="i_verify_that_the_Login_Button_Navigates_me_to_the_login_page_to_log_me_in_to_Cornwall" time="10.312" classname="Stepdef.Cornwall_Login_from_FUN"/>
  <testcase name="entering_the_correct_email_and_password_logs_me_in_to_Cornwall" time="7.310" classname="Stepdef.Cornwall_Login_from_FUN"/>
  <testcase name="verify_that_I_am_being_navigated_to_the_same_article_on_Cornwall" time="47.361" classname="Stepdef.Cornwall_Login_from_FUN">
    <failure type="java.lang.AssertionError" message="expected:&lt;0.2&gt; but was:&lt;-7.8&gt;">
      <![CDATA[java.lang.AssertionError: expected:<0.2> but was:<-7.8>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Cornwall_Login_from_FUN.verify_that_I_am_being_navigated_to_the_same_article_on_Cornwall(Cornwall_Login_from_FUN.java:198)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_that_I_am_being_navigated_to_the_same_article_on_Cornwall -->
</testsuite> <!-- Stepdef.Cornwall_Login_from_FUN -->
